name: Sample Conditional Job

on:
  push:
  pull_request: 
jobs:
  conditional-job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - run: echo "This only runs on main"
